### PR TITLE
WEB4709 : Content format is not retaining for the pasted data in the Email Editor

### PR DESCRIPTION
**Pull request by MahendarParakala**
If we paste the content which had PRE tags , the content is not retaining it's format and it's just showing it in a single line.

### CODE REVIEW

**Review by SuditiL — DISMISSED** [review]
Looks good...

**Review by StephenCavender — APPROVED** [review]

**Review by bhaskaraR — APPROVED** [review]
Approved. I suggest performing a squashed merge (since the pull request isn't a squashed one)

**Comment by SuditiL** [comment]
Ok to Squash and merge...

**Comment by MahendarParakala** [comment]
Squash Merged WEB4709 : Content format is not retaining for the pasted data in the Email Editor #98 from MahendarParakala:web-4709 to GenesysPureConnect:inin-master

**Pull request merged**
